global:
  scrape_interval: 5s

scrape_configs:
  - job_name: Prometheus
    static_configs:
      - targets: ["prometheus:9090"]
  # Add other services here
  - job_name: 'spring-batch-pushgateway'
    scrape_interval: 60s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']